{
 "title": "Kubernetes monitor Pods",
 "description": "Custom - Kubernetes to monitor POD statistics",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$Cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$Cluster\",node=~\"$Node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=\"$Cluster\",namespace=~\"$namespace\", pod=\"$pod\"}, container)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"\", container!=\"POD\"})",
     "legendFormat": "Current {{ pod }}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Request {{ pod }}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"$pod\", container=~\"$container\"}[$interval] ) )",
     "legendFormat": "Current"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_requests_cpu_cores{pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_receive_bytes_total{pod=~\"$pod\"}[$interval])))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}