{
 "title": "Kubernetes / Views / Namespaces",
 "description": "This is a modern 'Namespaces View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features (8.x.x). GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$Cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$Cluster\",node=~\"$Node\"}, namespace)"
    }
   },
   { "name": "resolution", "query": "1m, 2m, 3m, 5m" },
   {
    "name": "service",
    "query": {
     "query": "label_values(machine_cpu_cores, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (namespace/cluster)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", image!=\"\", service=\"$service\"}[$__rate_interval])) / sum(machine_cpu_cores{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "RAM Usage (namespace/cluster)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", service=\"$service\"}) / sum(machine_memory_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_secret_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_ingress_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{cluster=~\"$Cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Network Policies"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_hpa_labels{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Statefulsets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_labels{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_info{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU Used (namespace)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", image!=\"\", service=\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "RAM Used (namespace)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", service=\"$service\"})"
    }
   ]
  },
  {
   "title": "RAM Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Configmaps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_configmap_info{cluster=~\"$Cluster\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Failed Pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_phase{cluster=~\"$Cluster\",node=~\"$Node\",phase=\"Failed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pending Pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_phase{cluster=~\"$Cluster\",node=~\"$Node\",phase=\"Pending\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Unknown Pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_phase{cluster=~\"$Cluster\",node=~\"$Node\",phase=\"Unknown\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Evicted Pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_reason{cluster=~\"$Cluster\",node=~\"$Node\",reason=\"Evicted\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_status_ready{cluster=\"$Cluster\",node=~\"$Node\",condition=\"true\"}[$__range]))"
    }
   ]
  },
  { "title": "Namespaces/deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Nb  CrashLoopBackOff por NS ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "\r\nsum by (namespace)(changes(kube_pod_status_ready{cluster=~\"$Cluster\",node=~\"$Node\",condition=\"true\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Deployment unavailable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum by (deployment)(changes(kube_deployment_status_condition{cluster=~\"$Cluster\",node=~\"$Node\",condition=\"Available\",status=\"false\"}[$__range]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Replicas unavailable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum (changes (kube_deployment_status_replicas_unavailable{cluster=~\"$Cluster\",node=~\"$Node\"}[$__range])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "DaemonSet / StatefulSets / ReplicaSets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  },
  {
   "title": "Unavailable DaemonSet",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(changes(kube_daemonset_status_number_unavailable{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}[$__range])) by (daemonset)",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  {
   "title": "Total de  DaemonSet ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_ready{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}) by(daemonset)",
     "legendFormat": "{{daemonset}}"
    }
   ]
  },
  { "title": "Resources / service / endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", image!=\"\", service=\"$service\"}[$__range])) by (container)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Endpoint address not",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum (changes (kube_endpoint_address_not_ready{cluster=~\"$Cluster\",node=~\"$Node\"}[$__range])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Type of service",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum(kube_service_spec_type{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}) by (type)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Kubernetes Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Nb of pods by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})",
     "legendFormat": "Restarts Total"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"})",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Nb of replicas by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replicas available by deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Replicas unavailable by deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{cluster=~\"$Cluster\",node=~\"$Node\",namespace=~\"$namespace\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Persistent Volumes - Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", service=\"$service\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", service=\"$service\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_inodes_used{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", service=\"$service\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",namespace=~\"$namespace\", service=\"$service\"}) by (persistentvolumeclaim) * 100",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}