{
 "title": "Kubernetes Deployments -custom",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$Cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$Cluster\",node=~\"$Node\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": {
     "query": "label_values(kube_deployment_labels{cluster=~\"$Cluster\",namespace=~\"$namespace\",node=~\"$Node\"},deployment)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$Cluster\",namespace=~\"$namespace\", created_by_name=~\"$deployment-\\\\w{5,10}\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$Cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",pod=~\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",image!=\"\",container!=\"POD\",pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"$Node\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "Network I/O"
    }
   ]
  }
 ]
}