{
 "title": "Kubernetes Monitor",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Network/ Filesystem usage as well as individual pod, containers statistics. Uses cAdvisor and kube-state metrics only.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds{cluster=\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{node=\"$Node\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$Cluster\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) / sum (machine_cpu_cores{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$Cluster\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$Cluster\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$Cluster\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$Cluster\",id=\"/\"}[$__rate_interval])) / sum (machine_cpu_cores{cluster=~\"$Cluster\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"$Cluster\",id=\"/\", kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_hostname) / sum (machine_cpu_cores{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$Cluster\",id=\"/\"}) / sum (machine_memory_bytes{cluster=~\"$Cluster\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$Cluster\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname) / sum (machine_memory_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network I/O usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_hostname)",
     "legendFormat": "-> {{node}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_hostname)",
     "legendFormat": "<- {{node}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))",
     "legendFormat": "-> Cluster"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval]))",
     "legendFormat": "<- Cluster"
    }
   ]
  },
  {
   "title": "Filesystem I/O usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_hostname)",
     "legendFormat": "-> {{node}}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\"}[$__rate_interval])) by (kubernetes_io_hostname)",
     "legendFormat": "<- {{node}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\"}) / sum (container_fs_limit_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\"}) * 100",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, device) / sum (container_fs_limit_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, device) * 100",
     "legendFormat": "{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Capacity usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{cluster=~\"$Cluster\",device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) by (kubernetes_io_hostname, device)",
     "legendFormat": " {{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Numbers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=~\"$Cluster\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(kube_node_status_condition{cluster=~\"$Cluster\",condition=\"Ready\",status!=\"true\"})",
       "legendFormat": "Unavailable"
      }
     ]
    },
    {
     "title": "CPU requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",node=~\"^$Node$\", resource=\"cpu\"}) / sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"}) / sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Disk Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=~\"$Cluster\",node=~\"^$Node$\",condition=\"DiskPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Memory Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=~\"$Cluster\",node=~\"^$Node$\",condition=\"MemoryPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "PID Pressure",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=~\"$Cluster\",node=~\"^$Node$\",condition=\"PIDPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "CPU limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"cpu\"}) / sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"}) / sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Unschedulable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$Cluster\",node=~\"^$Node$\"})"
      }
     ]
    },
    {
     "title": "Out of Disk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=~\"$Cluster\",node=~\"^$Node$\",condition=\"OutOfDisk\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Network Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{cluster=~\"$Cluster\",node=~\"^$Node$\",condition=\"NetworkUnavailable\",status!=\"false\"})"
      }
     ]
    },
    {
     "title": "CPU Capacity / Allocatable / Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"cpu\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"cpu\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"cpu\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Memory Capacity / Allocatable / Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"memory\"})",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Storage Capacity / Allocatable / Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"ephemeral_storage\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"ephemeral_storage\"})",
       "legendFormat": "Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",node=~\"^$Node$\",resource=\"ephemeral_storage\"})",
       "legendFormat": "Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top-5 Deployment status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(5,kube_deployment_status_replicas_ready{cluster=~\"$Cluster\"}/(kube_deployment_status_replicas{cluster=~\"$Cluster\"}>0))",
       "legendFormat": "{{exported_namespace}}/{{ deployment }}"
      }
     ]
    },
    {
     "title": "Top-5 Daemonset status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(5,kube_daemonset_status_number_ready{cluster=~\"$Cluster\"}/(kube_daemonset_status_desired_number_scheduled{cluster=~\"$Cluster\"}>0))",
       "legendFormat": "{{exported_namespace}}/{{ daemonset}}"
      }
     ]
    },
    {
     "title": "Top-5 Job Status",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "bottomk(5,sum(kube_job_status_succeeded{cluster=~\"$Cluster\"} / kube_job_spec_completions{cluster=~\"$Cluster\"}) by (job_name,exported_namespace))",
       "legendFormat": "{{exported_namespace}}/{{ job_name}}"
      }
     ]
    },
    {
     "title": "Pod  status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$Cluster\"}) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "Container status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{cluster=~\"$Cluster\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{cluster=~\"$Cluster\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{cluster=~\"$Cluster\"})",
       "legendFormat": "Terminated"
      }
     ]
    },
    {
     "title": "CPU vCores Requested by Pod",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "suffix:m" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",resource=\"cpu\"}) by (pod) * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory  Requested by Pod",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$Cluster\",resource=\"memory\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Top-10 Pod Restarts (Last 30 Minutes)",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10,sum(delta(kube_pod_container_status_restarts_total{cluster=~\"$Cluster\"}[30m])) by (pod)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod CPU / Memory / Network / Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container!=\"POD\",container!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Memory  usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container!=\"POD\",container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Network I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container=~\"^(POD)?$\"}[$__rate_interval])) by (pod)",
       "legendFormat": "-> {{ pod}}"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container=~\"^(POD)?$\"}[$__rate_interval])) by (pod)",
       "legendFormat": "<- {{ pod}}"
      }
     ]
    },
    {
     "title": "Pod Filesystem I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",pod!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "-> {{ pod}}"
      },
      {
       "expr": "-sum(rate(container_fs_reads_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",pod!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "<- {{ pod}}"
      }
     ]
    },
    {
     "title": "Pod Filesystem  usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container!=\"^(POD)?$\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container CPU / Memory / Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container!=\"POD\",container!=\"\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "{{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Container Memory  usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container!~\"^(POD)?$\"}) by (pod,container)",
       "legendFormat": "{{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Container Filesystem I/O usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",container!~\"^(POD)?$\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "-> {{ pod}} | {{container}}"
      },
      {
       "expr": "-sum(rate(container_fs_reads_bytes_total{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$POD$\",container!~\"^(POD)?$\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "<- {{ pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Container Filesystem  usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{cluster=~\"$Cluster\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pod$\",image!=\"\",container!~\"^(POD)?$\"}) by (pod,container)",
       "legendFormat": "{{pod}} | {{container}}"
      }
     ]
    }
   ]
  }
 ]
}